### ISSUE TITLE
address already  in use 

### ISSUE THREAD

**Issue by WangHexie** [fbkcs/ThunderDNS#1]
`System`: Ubuntu 18.04   

```
@instance-2:~/ThunderDNS$ sudo python3 ./server.py --domain mydomin
 ________________               _________         _______________   _________
 ___/__  __/__/ /_____  ______________/ /______________/ __ \__/ | / //_ ___/
 _____/ /____/ __ \  / / /_/ __ \/ __  /_/ _ \_/ __/ _/ / / /_/  |/ //____ \ 
 ____/ /____/ / / / /_/ /_  / / / /_/ / /  __// /  __/ /_/ /_/ /|  / ____/ / 
 ___/_/____/_/ /_/\__,_/ /_/ /_/\__,_/__\___//_/  __/_____/ /_/ |_/ /_____/  
Starting DNS server...
Traceback (most recent call last):
  File "./server.py", line 330, in <module>
    tcp_server = DNSServer(resolver, port=port, tcp=True)
  File "/usr/local/lib/python3.6/dist-packages/dnslib/server.py", line 343, in __init__
    self.server = server((address,port),handler)
  File "/usr/lib/python3.6/socketserver.py", line 453, in __init__
    self.server_bind()
  File "/usr/lib/python3.6/socketserver.py", line 467, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
```   
Then  I used command `lsof -i:53`, no return.

**Comment by WangHexie** [comment]
`sudo` !!!!!!!!!!!!!!!!!!!

**Comment by calvingalabuzi** [comment]
root@myserver:~/ThunderDNS# sudo python3 server.py -d 0.0.0.0
 ________________               _________         _______________   _________
 ___/__  __/__/ /_____  ______________/ /______________/ __ \__/ | / //_ ___/
 _____/ /____/ __ \  / / /_/ __ \/ __  /_/ _ \_/ __/ _/ / / /_/  |/ //____ \
 ____/ /____/ / / / /_/ /_  / / / /_/ / /  __// /  __/ /_/ /_/ /|  / ____/ /
 ___/_/____/_/ /_/\__,_/ /_/ /_/\__,_/__\___//_/  __/_____/ /_/ |_/ /_____/
Starting DNS server...
Traceback (most recent call last):
  File "server.py", line 331, in <module>
    proxy_handler = ProxyHandler('', port=proxy_port, delay=delay_size, buffer_size=buffer_size)
  File "server.py", line 84, in __init__
    self.server.listen(200)
OSError: [Errno 98] Address already in use
root@myserver:~/ThunderDNS#
